# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jENv_bUpb2rsOS2lLxA1Q4TdmFC7brfQ

1.Find the largest element in a list
"""

numbers = [45, 12, 98, 23, 7, 150, 67]
print("Largest:", max(numbers))

"""2. check if a number is even or odd"""

num = 21
print("Even" if num % 2 == 0 else "Odd")

"""3. reverse a string"""

text = "Hello"
rev = ""
for ch in text:
    rev = ch + rev
print("Reversed:", rev)

"""4. count vowels in a string

"""

text = "Hello World"
vowels = "aeiouAEIOU"
count = sum(1 for ch in text if ch in vowels)
print("Vowel count:", count)

"""5.find the sum of digits of a number."""

num = 12345
sum_digits = sum(int(d) for d in str(num))
print("Sum of digits:", sum_digits)

"""6. check if the string is palindrome or not

"""

text = "madam"
print("Palindrome" if text == text[::-1] else "Not Palindrome")

"""7.print fibbonacci seriers upto n terms"""

n = 10
a, b = 0, 1
for _ in range(n):
    print(a, end=" ")
    a, b = b, a + b

"""8.Swap two variables without a third variable."""

a, b = 5, 10
a, b = b, a
print("a:", a, "b:", b)

"""9.Count words in a sentence"""

sentence = "Python is fun to learn"
words = sentence.split()
print("Word count:", len(words))

"""10.Find minimum and maximum in a list"""

numbers = [45, 12, 98, 23, 7, 150, 67]
print("Min:", min(numbers), "Max:", max(numbers))

"""11.Find the second largest number in a list"""

numbers = [45, 12, 98, 23, 7, 150, 67]
second_largest = sorted(set(numbers))[-2]
print("Second largest:", second_largest)

"""12.Remove duplicates from a list (without set)"""

numbers = [1, 2, 2, 3, 4, 4, 5]
unique = []
for n in numbers:
    if n not in unique:
        unique.append(n)
print("Without duplicates:", unique)

"""13.count frequency of elements in a list."""

numbers = [1, 2, 2, 3, 4, 4, 5]
freq = {}
for n in numbers:
    freq[n] = freq.get(n, 0) + 1
print("Frequencies:", freq)

"""14.Merge two sorted lists."""

list1 = [1, 3, 5]
list2 = [2, 4, 6]
merged = sorted(list1 + list2)
print("Merged:", merged)

"""15.Find the intersection of two lists."""

list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]
intersection = [x for x in list1 if x in list2]
print("Intersection:", intersection)

"""16.Rotate a list by k positions."""

numbers = [1, 2, 3, 4, 5]
k = 2
rotated = numbers[k:] + numbers[:k]
print("Rotated:", rotated)

"""17.Check if two strings are anagrams."""

s1, s2 = "listen", "silent"
print("Anagram" if sorted(s1) == sorted(s2) else "Not Anagram")

"""18.Find the first non-repeating character."""

text = "swiss"
for ch in text:
    if text.count(ch) == 1:
        print("First non-repeating:", ch)
        break

"""19.Flatten a nested list."""

nested = [[1, 2], [3, 4], [5]]
flat = [item for sublist in nested for item in sublist]
print("Flattened:", flat)

"""20.Find all pairs with a given sum"""

numbers = [1, 2, 3, 4, 5]
target = 6
pairs = [(a, b) for i, a in enumerate(numbers) for b in numbers[i+1:] if a + b == target]
print("Pairs:", pairs)

"""21.Print a right triangle pattern."""

n = 5
for i in range(1, n+1):
    print("*" * i)

"""22.Print a pyramid pattern."""

n = 5
for i in range(1, n+1):
    print(" " * (n-i) + "*" * (2*i-1))

"""23.Print all prime numbers in a range."""

start, end = 10, 50
for num in range(start, end+1):
    if num > 1:
        for i in range(2, int(num**0.5)+1):
            if num % i == 0:
                break
        else:
            print(num, end=" ")

"""24.Check if a number is Armstrong"""

num = 153
power = len(str(num))
sum_digits = sum(int(d)**power for d in str(num))
print("Armstrong" if sum_digits == num else "Not Armstrong")
